### ISSUE TITLE
install Doc

### ISSUE THREAD

**Issue by aref-rf** [voiceip/mod_event_kafka#12]
hello
can you complete your readme, i can not install it.
can i use kafka in freeswitch?

**Comment by kingster** [comment]
Hi

What error are you facing? Can you share the error ?

> can i use kafka in freeswitch?

yes, this would allow to publish events to a kafka.

**Comment by tanish20j** [comment]
Can someone update the documentation ?

**Comment by kingster** [comment]
@tanish20j what step documentation are you looking for which is not available?

**Comment by aref-rf** [comment]
> 

hello again
i have not installed it yet
i'm wonder if i can use it in cdr json
to send cdr json http request to kafka
is it possible?

**Comment by kingster** [comment]
Hi @tanish20j 

>  Documentation related which compression is supported 

The compressions formats that are supported is what the kafka-client supports. As per their documentation at https://github.com/confluentinc/librdkafka#features it supports `snappy, gzip, lz4, zstd`

> how to build along with freeswitch, or which freeswitch versions are supported or tested.

In order to build you can follow the build instructions at our read-me https://github.com/voiceip/mod_event_kafka#manually-building. On production, I am using it against 1.10 (we haven't upgraded in a really long time), and it should work with any version above it. 

> Also can I pass custom events in kafka ?

As long as you are raisng events to freeswitch all events would be published automatically from fs to this module, and then it would be transmitted to kafka.

**Comment by kingster** [comment]
Hi @aref-rf

> i'm wonder if i can use it in cdr json
> to send cdr json http request to kafka

No, this module is not meant for that. This module can publish events that are raised by freeswitch to kafka. cdr json is a different module and you would have to request them to support sending to different sink (kafka) instead of the filesystem where they publish it. 

However, you would be getting the raw call events in kafka which would allow you to compute the cdr in the application that consumers by using the `CALL_REPORTING` event which would contain all of the necessary details.
